### ISSUE TITLE
[block-html5-p2p]部分站点无法成功屏蔽

### ISSUE THREAD

**Issue by WankkoRee** [binsee/tampermonkey-scripts#3]
站点：[VoidSec](https://ip.voidsec.com/)
在`chrome://webrtc-internals/`中还是可以看见连接被成功创建。
![image](https://user-images.githubusercontent.com/21287731/129579431-60b975eb-ef6c-420b-919c-25685382debb.png)

日志中也没有debug出`PeerConnection() 被调用`的字样。
![image](https://user-images.githubusercontent.com/21287731/129579569-c6fe2b07-bd32-4d7f-a73e-f90982a27651.png)

**Comment by binsee** [comment]
已更新，请使用 0.1.4 版本进行测试

**Comment by WankkoRee** [comment]
感谢，它正常工作了！
